# Generated by Django 5.1.3 on 2025-05-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='data_uploads/')),
                ('file_type', models.CharField(choices=[('csv', 'CSV'), ('xls', 'Excel (.xls)'), ('xlsx', 'Excel (.xlsx)'), ('dta', 'Stata (.dta)'), ('sav', 'SPSS (.sav)'), ('sps', 'SPSS (.sps)'), ('spv', 'SPSS (.spv)')], editable=False, max_length=10)),
                ('source_type', models.CharField(blank=True, choices=[('internal', 'Internal'), ('external', 'External')], max_length=10, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('survey_name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('time_frequency', models.CharField(blank=True, choices=[('After 5 years', 'After 5 years'), ('After 4 years', 'After 4 years'), ('After 3 years', 'After 3 years'), ('After 2 years', 'After 2 years'), ('annual', 'Annual'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly')], max_length=20, null=True)),
                ('internal_description', models.TextField(blank=True, help_text='Indicators defined by admin (predefined before Elasticsearch)', null=True)),
                ('external_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_section_from', models.CharField(blank=True, max_length=255, null=True)),
                ('external_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
