# Generated by Django 5.2.1 on 2025-05-12 08:40

import GDL_Full.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDL_Full', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('survey_id', models.AutoField(primary_key=True, serialize=False)),
                ('survey_name', models.CharField(max_length=250)),
                ('year', models.DateField(validators=[GDL_Full.models.validate_year_only])),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_name', models.CharField(max_length=250)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='GDL_Full.survey')),
            ],
        ),
    ]
