# Generated by Django 5.2.1 on 2025-05-12 08:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDL_Full', '0002_survey_indicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='survey_files/'),
            preserve_default=False,
        ),
    ]
