# Generated by Django 5.2.1 on 2025-05-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDL_Full', '0003_survey_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_name',
            field=models.CharField(choices=[('integrated_business_survey', 'Integrated Business Enterprise Survey'), ('eicv', 'Integrated Household Living Conditions Survey (EICV)'), ('labour_force_survey', 'Labour Force Survey')], max_length=100),
        ),
    ]
